<?php

namespace LP\ReservationBundle\Repository;

/**
 * ReservationDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationDateRepository extends \Doctrine\ORM\EntityRepository
{
	public function sumTicketOftheday($id)
	{
		//$date = date('2017-09-25');
		return $this->createQueryBuilder('r')
		            ->select('SUM(r.number)')
		            ->andWhere('r.dated = :dated ')
		            ->setParameter('dated', $id)
		            ->getQuery()
		            ->getSingleScalarResult();		
	}

	public function getReservationDate($id)
	{
		return $this
		     ->createQueryBuilder('r')
		     ->select('r.dated')
		     ->andWhere('r.id = :id')
		     ->setParameter('id',$id)
		     ->getQuery()
		     ->getSingleScalarResult();
	}

}
