<?php

namespace LP\ReservationBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{
	public function getReservationWithReservationDate()
	{
		return $this
		  ->createQueryBuilder('r')
		  ->innerJoin('r.reservationdate','res')
		  ->addSelect('res')
          ->getQuery()
          ->getResult();
	}

	public function getIdReservation($id)
	{
		return $this
		  ->createQueryBuilder('r')
		  ->innerJoin('r.reservationdate','res')
		  ->addSelect('res')
		  ->Select('res.id ')
		  ->andWhere('res.id = :$id')
		  ->setParameter('id',$id)
		  ->getQuery()
		  ->getSingleScalarResult();

	}

	
}
