<?php

namespace LP\ReservationBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{
	public function getBirthday($birthday)
	{
		return $this
		  ->createQueryBuilder('t')
		  ->select('t.birthday')
		  ->andWhere('t.birthday = :birthday')
		  ->setParameter('birthday' ,$birthday)
		  ->getQuery()
		  ->getResult();
	}

	public function findAllTicketForReservationDate($reservationDate){

	    return $this
            ->createQueryBuilder('t')
            ->select('COUNT(t)')
            ->innerJoin('t.reservation','r')
            ->andWhere('r.reservationdate = :reservationdate')
            ->setParameter('reservationdate',$reservationDate)
            ->getQuery()
            ->getSingleScalarResult();

    }


	public function getSumTicketsWithReservation($id)
	{
		return $this
		  ->createQueryBuilder('t')
		  ->select('SUM(t.price)')
		  ->andWhere('t.reservation = :id')
		  ->setParameter('id', $id)
		  ->getQuery()
		  ->getSingleScalarResult();
	}

	public function getListTicketsWithReservation($id)
	{
		return $this
		  ->createQueryBuilder('t')
		  ->select('t')
		  ->andWhere('t.reservation = :id')
		  ->setParameter('id',$id)
		  ->getQuery()
		  ->getResult();
	}

	public function sumTicketsWithId($reservationId)
	{
		return $this
		   ->createQueryBuilder('t')
		   ->select('t')
		   ->andWhere('t.reservation = :reservationId')
		   ->setParameter('reservationId',$reservationId)
		   ->getQuery()
		   ->getScalarResult();
	}
}
